/* automatically generated by rust-bindgen 0.72.1 */

pub const AI_CONFIG_GLOB_MEASURE_TIME: &[u8; 18] = b"GLOB_MEASURE_TIME\0";
pub const AI_CONFIG_IMPORT_NO_SKELETON_MESHES: &[u8; 26] = b"IMPORT_NO_SKELETON_MESHES\0";
pub const AI_CONFIG_PP_SBBC_MAX_BONES: &[u8; 18] = b"PP_SBBC_MAX_BONES\0";
pub const AI_SBBC_DEFAULT_MAX_BONES: u32 = 60;
pub const AI_CONFIG_PP_CT_MAX_SMOOTHING_ANGLE: &[u8; 26] = b"PP_CT_MAX_SMOOTHING_ANGLE\0";
pub const AI_CONFIG_PP_CT_TEXTURE_CHANNEL_INDEX: &[u8; 28] = b"PP_CT_TEXTURE_CHANNEL_INDEX\0";
pub const AI_CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE: &[u8; 27] = b"PP_GSN_MAX_SMOOTHING_ANGLE\0";
pub const AI_CONFIG_IMPORT_MDL_COLORMAP: &[u8; 20] = b"IMPORT_MDL_COLORMAP\0";
pub const AI_CONFIG_PP_RRM_EXCLUDE_LIST: &[u8; 20] = b"PP_RRM_EXCLUDE_LIST\0";
pub const AI_CONFIG_PP_PTV_KEEP_HIERARCHY: &[u8; 22] = b"PP_PTV_KEEP_HIERARCHY\0";
pub const AI_CONFIG_PP_PTV_NORMALIZE: &[u8; 17] = b"PP_PTV_NORMALIZE\0";
pub const AI_CONFIG_PP_PTV_ADD_ROOT_TRANSFORMATION: &[u8; 31] = b"PP_PTV_ADD_ROOT_TRANSFORMATION\0";
pub const AI_CONFIG_PP_PTV_ROOT_TRANSFORMATION: &[u8; 27] = b"PP_PTV_ROOT_TRANSFORMATION\0";
pub const AI_CONFIG_CHECK_IDENTITY_MATRIX_EPSILON: &[u8; 30] = b"CHECK_IDENTITY_MATRIX_EPSILON\0";
pub const AI_CONFIG_CHECK_IDENTITY_MATRIX_EPSILON_DEFAULT: f64 = 0.01;
pub const AI_CONFIG_PP_FD_REMOVE: &[u8; 13] = b"PP_FD_REMOVE\0";
pub const AI_CONFIG_PP_FD_CHECKAREA: &[u8; 16] = b"PP_FD_CHECKAREA\0";
pub const AI_CONFIG_PP_OG_EXCLUDE_LIST: &[u8; 19] = b"PP_OG_EXCLUDE_LIST\0";
pub const AI_CONFIG_PP_SLM_TRIANGLE_LIMIT: &[u8; 22] = b"PP_SLM_TRIANGLE_LIMIT\0";
pub const AI_SLM_DEFAULT_MAX_TRIANGLES: u32 = 1000000;
pub const AI_CONFIG_PP_SLM_VERTEX_LIMIT: &[u8; 20] = b"PP_SLM_VERTEX_LIMIT\0";
pub const AI_SLM_DEFAULT_MAX_VERTICES: u32 = 1000000;
pub const AI_CONFIG_PP_LBW_MAX_WEIGHTS: &[u8; 19] = b"PP_LBW_MAX_WEIGHTS\0";
pub const AI_LMW_MAX_WEIGHTS: u32 = 4;
pub const AI_CONFIG_PP_DB_THRESHOLD: &[u8; 16] = b"PP_DB_THRESHOLD\0";
pub const AI_DEBONE_THRESHOLD: f64 = 1.0;
pub const AI_CONFIG_PP_DB_ALL_OR_NONE: &[u8; 18] = b"PP_DB_ALL_OR_NONE\0";
pub const AI_CONFIG_PP_ICL_PTCACHE_SIZE: &[u8; 20] = b"PP_ICL_PTCACHE_SIZE\0";
pub const AI_CONFIG_PP_RVC_FLAGS: &[u8; 13] = b"PP_RVC_FLAGS\0";
pub const AI_CONFIG_PP_SBP_REMOVE: &[u8; 14] = b"PP_SBP_REMOVE\0";
pub const AI_CONFIG_PP_FID_ANIM_ACCURACY: &[u8; 21] = b"PP_FID_ANIM_ACCURACY\0";
pub const AI_CONFIG_PP_FID_IGNORE_TEXTURECOORDS: &[u8; 28] = b"PP_FID_IGNORE_TEXTURECOORDS\0";
pub const AI_UVTRAFO_SCALING: u32 = 1;
pub const AI_UVTRAFO_ROTATION: u32 = 2;
pub const AI_UVTRAFO_TRANSLATION: u32 = 4;
pub const AI_UVTRAFO_ALL: u32 = 7;
pub const AI_CONFIG_PP_TUV_EVALUATE: &[u8; 16] = b"PP_TUV_EVALUATE\0";
pub const AI_CONFIG_FAVOUR_SPEED: &[u8; 13] = b"FAVOUR_SPEED\0";
pub const AI_CONFIG_IMPORT_SCHEMA_DOCUMENT_PROVIDER: &[u8; 32] =
    b"IMPORT_SCHEMA_DOCUMENT_PROVIDER\0";
pub const AI_CONFIG_IMPORT_FBX_READ_ALL_GEOMETRY_LAYERS: &[u8; 36] =
    b"IMPORT_FBX_READ_ALL_GEOMETRY_LAYERS\0";
pub const AI_CONFIG_IMPORT_FBX_READ_ALL_MATERIALS: &[u8; 30] = b"IMPORT_FBX_READ_ALL_MATERIALS\0";
pub const AI_CONFIG_IMPORT_FBX_READ_MATERIALS: &[u8; 26] = b"IMPORT_FBX_READ_MATERIALS\0";
pub const AI_CONFIG_IMPORT_FBX_READ_TEXTURES: &[u8; 25] = b"IMPORT_FBX_READ_TEXTURES\0";
pub const AI_CONFIG_IMPORT_FBX_READ_CAMERAS: &[u8; 24] = b"IMPORT_FBX_READ_CAMERAS\0";
pub const AI_CONFIG_IMPORT_FBX_READ_LIGHTS: &[u8; 23] = b"IMPORT_FBX_READ_LIGHTS\0";
pub const AI_CONFIG_IMPORT_FBX_READ_ANIMATIONS: &[u8; 27] = b"IMPORT_FBX_READ_ANIMATIONS\0";
pub const AI_CONFIG_IMPORT_FBX_READ_WEIGHTS: &[u8; 24] = b"IMPORT_FBX_READ_WEIGHTS\0";
pub const AI_CONFIG_IMPORT_FBX_STRICT_MODE: &[u8; 23] = b"IMPORT_FBX_STRICT_MODE\0";
pub const AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS: &[u8; 27] = b"IMPORT_FBX_PRESERVE_PIVOTS\0";
pub const AI_CONFIG_IMPORT_FBX_OPTIMIZE_EMPTY_ANIMATION_CURVES: &[u8; 43] =
    b"IMPORT_FBX_OPTIMIZE_EMPTY_ANIMATION_CURVES\0";
pub const AI_CONFIG_IMPORT_FBX_EMBEDDED_TEXTURES_LEGACY_NAMING: &[u8; 53] =
    b"AI_CONFIG_IMPORT_FBX_EMBEDDED_TEXTURES_LEGACY_NAMING\0";
pub const AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES: &[u8; 36] = b"AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES\0";
pub const AI_CONFIG_FBX_CONVERT_TO_M: &[u8; 27] = b"AI_CONFIG_FBX_CONVERT_TO_M\0";
pub const AI_CONFIG_IMPORT_FBX_IGNORE_UP_DIRECTION: &[u8; 41] =
    b"AI_CONFIG_IMPORT_FBX_IGNORE_UP_DIRECTION\0";
pub const AI_CONFIG_FBX_USE_SKELETON_BONE_CONTAINER: &[u8; 42] =
    b"AI_CONFIG_FBX_USE_SKELETON_BONE_CONTAINER\0";
pub const AI_CONFIG_IMPORT_GLOBAL_KEYFRAME: &[u8; 23] = b"IMPORT_GLOBAL_KEYFRAME\0";
pub const AI_CONFIG_IMPORT_MD3_KEYFRAME: &[u8; 20] = b"IMPORT_MD3_KEYFRAME\0";
pub const AI_CONFIG_IMPORT_MD2_KEYFRAME: &[u8; 20] = b"IMPORT_MD2_KEYFRAME\0";
pub const AI_CONFIG_IMPORT_MDL_KEYFRAME: &[u8; 20] = b"IMPORT_MDL_KEYFRAME\0";
pub const AI_CONFIG_IMPORT_MDC_KEYFRAME: &[u8; 20] = b"IMPORT_MDC_KEYFRAME\0";
pub const AI_CONFIG_IMPORT_SMD_KEYFRAME: &[u8; 20] = b"IMPORT_SMD_KEYFRAME\0";
pub const AI_CONFIG_IMPORT_UNREAL_KEYFRAME: &[u8; 23] = b"IMPORT_UNREAL_KEYFRAME\0";
pub const AI_CONFIG_IMPORT_MDL_HL1_READ_ANIMATIONS: &[u8; 31] = b"IMPORT_MDL_HL1_READ_ANIMATIONS\0";
pub const AI_CONFIG_IMPORT_MDL_HL1_READ_ANIMATION_EVENTS: &[u8; 37] =
    b"IMPORT_MDL_HL1_READ_ANIMATION_EVENTS\0";
pub const AI_CONFIG_IMPORT_MDL_HL1_TRANSFORM_COORD_SYSTEM: &[u8; 37] =
    b"TRANSFORM COORDSYSTEM FOR HS! MODELS\0";
pub const AI_CONFIG_IMPORT_MDL_HL1_READ_BLEND_CONTROLLERS: &[u8; 38] =
    b"IMPORT_MDL_HL1_READ_BLEND_CONTROLLERS\0";
pub const AI_CONFIG_IMPORT_MDL_HL1_READ_SEQUENCE_TRANSITIONS: &[u8; 41] =
    b"IMPORT_MDL_HL1_READ_SEQUENCE_TRANSITIONS\0";
pub const AI_CONFIG_IMPORT_MDL_HL1_READ_ATTACHMENTS: &[u8; 32] =
    b"IMPORT_MDL_HL1_READ_ATTACHMENTS\0";
pub const AI_CONFIG_IMPORT_MDL_HL1_READ_BONE_CONTROLLERS: &[u8; 37] =
    b"IMPORT_MDL_HL1_READ_BONE_CONTROLLERS\0";
pub const AI_CONFIG_IMPORT_MDL_HL1_READ_HITBOXES: &[u8; 29] = b"IMPORT_MDL_HL1_READ_HITBOXES\0";
pub const AI_CONFIG_IMPORT_MDL_HL1_READ_MISC_GLOBAL_INFO: &[u8; 37] =
    b"IMPORT_MDL_HL1_READ_MISC_GLOBAL_INFO\0";
pub const AI_CONFIG_IMPORT_SMD_LOAD_ANIMATION_LIST: &[u8; 31] = b"IMPORT_SMD_LOAD_ANIMATION_LIST\0";
pub const AI_CONFIG_IMPORT_AC_SEPARATE_BFCULL: &[u8; 26] = b"IMPORT_AC_SEPARATE_BFCULL\0";
pub const AI_CONFIG_IMPORT_AC_EVAL_SUBDIVISION: &[u8; 27] = b"IMPORT_AC_EVAL_SUBDIVISION\0";
pub const AI_CONFIG_IMPORT_UNREAL_HANDLE_FLAGS: &[u8; 20] = b"UNREAL_HANDLE_FLAGS\0";
pub const AI_CONFIG_IMPORT_TER_MAKE_UVS: &[u8; 20] = b"IMPORT_TER_MAKE_UVS\0";
pub const AI_CONFIG_IMPORT_ASE_RECONSTRUCT_NORMALS: &[u8; 31] = b"IMPORT_ASE_RECONSTRUCT_NORMALS\0";
pub const AI_CONFIG_IMPORT_MD3_HANDLE_MULTIPART: &[u8; 28] = b"IMPORT_MD3_HANDLE_MULTIPART\0";
pub const AI_CONFIG_IMPORT_MD3_SKIN_NAME: &[u8; 21] = b"IMPORT_MD3_SKIN_NAME\0";
pub const AI_CONFIG_IMPORT_MD3_LOAD_SHADERS: &[u8; 24] = b"IMPORT_MD3_LOAD_SHADERS\0";
pub const AI_CONFIG_IMPORT_MD3_SHADER_SRC: &[u8; 22] = b"IMPORT_MD3_SHADER_SRC\0";
pub const AI_CONFIG_IMPORT_LWO_ONE_LAYER_ONLY: &[u8; 26] = b"IMPORT_LWO_ONE_LAYER_ONLY\0";
pub const AI_CONFIG_IMPORT_MD5_NO_ANIM_AUTOLOAD: &[u8; 28] = b"IMPORT_MD5_NO_ANIM_AUTOLOAD\0";
pub const AI_CONFIG_IMPORT_LWS_ANIM_START: &[u8; 22] = b"IMPORT_LWS_ANIM_START\0";
pub const AI_CONFIG_IMPORT_LWS_ANIM_END: &[u8; 20] = b"IMPORT_LWS_ANIM_END\0";
pub const AI_CONFIG_IMPORT_IRR_ANIM_FPS: &[u8; 20] = b"IMPORT_IRR_ANIM_FPS\0";
pub const AI_CONFIG_IMPORT_OGRE_MATERIAL_FILE: &[u8; 26] = b"IMPORT_OGRE_MATERIAL_FILE\0";
pub const AI_CONFIG_IMPORT_OGRE_TEXTURETYPE_FROM_FILENAME: &[u8; 38] =
    b"IMPORT_OGRE_TEXTURETYPE_FROM_FILENAME\0";
pub const AI_CONFIG_ANDROID_JNI_ASSIMP_MANAGER_SUPPORT: &[u8; 45] =
    b"AI_CONFIG_ANDROID_JNI_ASSIMP_MANAGER_SUPPORT\0";
pub const AI_CONFIG_IMPORT_IFC_SKIP_SPACE_REPRESENTATIONS: &[u8; 38] =
    b"IMPORT_IFC_SKIP_SPACE_REPRESENTATIONS\0";
pub const AI_CONFIG_IMPORT_IFC_CUSTOM_TRIANGULATION: &[u8; 32] =
    b"IMPORT_IFC_CUSTOM_TRIANGULATION\0";
pub const AI_CONFIG_IMPORT_IFC_SMOOTHING_ANGLE: &[u8; 27] = b"IMPORT_IFC_SMOOTHING_ANGLE\0";
pub const AI_IMPORT_IFC_DEFAULT_SMOOTHING_ANGLE: f64 = 10.0;
pub const AI_CONFIG_IMPORT_IFC_CYLINDRICAL_TESSELLATION: &[u8; 36] =
    b"IMPORT_IFC_CYLINDRICAL_TESSELLATION\0";
pub const AI_IMPORT_IFC_DEFAULT_CYLINDRICAL_TESSELLATION: u32 = 32;
pub const AI_CONFIG_IMPORT_COLLADA_IGNORE_UP_DIRECTION: &[u8; 35] =
    b"IMPORT_COLLADA_IGNORE_UP_DIRECTION\0";
pub const AI_CONFIG_IMPORT_COLLADA_IGNORE_UNIT_SIZE: &[u8; 32] =
    b"IMPORT_COLLADA_IGNORE_UNIT_SIZE\0";
pub const AI_CONFIG_IMPORT_COLLADA_USE_COLLADA_NAMES: &[u8; 33] =
    b"IMPORT_COLLADA_USE_COLLADA_NAMES\0";
pub const AI_CONFIG_EXPORT_XFILE_64BIT: &[u8; 19] = b"EXPORT_XFILE_64BIT\0";
pub const AI_CONFIG_EXPORT_POINT_CLOUDS: &[u8; 20] = b"EXPORT_POINT_CLOUDS\0";
pub const AI_CONFIG_USE_GLTF_PBR_SPECULAR_GLOSSINESS: &[u8; 33] =
    b"USE_GLTF_PBR_SPECULAR_GLOSSINESS\0";
pub const AI_CONFIG_EXPORT_GLTF_UNLIMITED_SKINNING_BONES_PER_VERTEX: &[u8; 31] =
    b"USE_UNLIMITED_BONES_PER VERTEX\0";
pub const AI_CONFIG_EXPORT_FBX_TRANSPARENCY_FACTOR_REFER_TO_OPACITY: &[u8; 48] =
    b"EXPORT_FBX_TRANSPARENCY_FACTOR_REFER_TO_OPACITY\0";
pub const AI_CONFIG_EXPORT_BLOB_NAME: &[u8; 17] = b"EXPORT_BLOB_NAME\0";
pub const AI_CONFIG_GLOBAL_SCALE_FACTOR_KEY: &[u8; 20] = b"GLOBAL_SCALE_FACTOR\0";
pub const AI_CONFIG_GLOBAL_SCALE_FACTOR_DEFAULT: f64 = 1.0;
pub const AI_CONFIG_APP_SCALE_KEY: &[u8; 17] = b"APP_SCALE_FACTOR\0";
pub const AI_MATH_PI: f64 = 3.141592653589793;
pub const AI_MATH_TWO_PI: f64 = 6.283185307179586;
pub const AI_MATH_HALF_PI: f64 = 1.5707963267948966;
pub const AI_MATH_PI_F: f64 = 3.1415926538;
pub const AI_MATH_TWO_PI_F: f64 = 6.2831853076;
pub const AI_MATH_HALF_PI_F: f64 = 1.5707963269;
pub const AI_MAXLEN: u32 = 1024;
pub const AI_FALSE: u32 = 0;
pub const AI_TRUE: u32 = 1;
pub const AI_EMBEDDED_TEXNAME_PREFIX: &[u8; 2] = b"*\0";
pub const AI_MAX_FACE_INDICES: u32 = 32767;
pub const AI_MAX_BONE_WEIGHTS: u32 = 2147483647;
pub const AI_MAX_VERTICES: u32 = 2147483647;
pub const AI_MAX_FACES: u32 = 2147483647;
pub const AI_MAX_NUMBER_OF_COLOR_SETS: u32 = 8;
pub const AI_MAX_NUMBER_OF_TEXTURECOORDS: u32 = 8;
pub const AI_DEFAULT_MATERIAL_NAME: &[u8; 16] = b"DefaultMaterial\0";
pub const AI_SCENE_FLAGS_INCOMPLETE: u32 = 1;
pub const AI_SCENE_FLAGS_VALIDATED: u32 = 2;
pub const AI_SCENE_FLAGS_VALIDATION_WARNING: u32 = 4;
pub const AI_SCENE_FLAGS_NON_VERBOSE_FORMAT: u32 = 8;
pub const AI_SCENE_FLAGS_TERRAIN: u32 = 16;
pub const AI_SCENE_FLAGS_ALLOW_SHARED: u32 = 32;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiComponent {
    aiComponent_NORMALS = 2,
    aiComponent_TANGENTS_AND_BITANGENTS = 4,
    aiComponent_COLORS = 8,
    aiComponent_TEXCOORDS = 16,
    aiComponent_BONEWEIGHTS = 32,
    aiComponent_ANIMATIONS = 64,
    aiComponent_TEXTURES = 128,
    aiComponent_LIGHTS = 256,
    aiComponent_CAMERAS = 512,
    aiComponent_MESHES = 1024,
    aiComponent_MATERIALS = 2048,
    _aiComponent_Force32Bit = 2684354559,
}
pub type ai_real = f32;
pub type ai_int = ::std::os::raw::c_int;
pub type ai_uint = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiVector2D {
    pub x: ai_real,
    pub y: ai_real,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiVector3D {
    pub x: ai_real,
    pub y: ai_real,
    pub z: ai_real,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiColor4D {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiMatrix3x3 {
    pub a1: ai_real,
    pub a2: ai_real,
    pub a3: ai_real,
    pub b1: ai_real,
    pub b2: ai_real,
    pub b3: ai_real,
    pub c1: ai_real,
    pub c2: ai_real,
    pub c3: ai_real,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiMatrix4x4 {
    pub a1: ai_real,
    pub a2: ai_real,
    pub a3: ai_real,
    pub a4: ai_real,
    pub b1: ai_real,
    pub b2: ai_real,
    pub b3: ai_real,
    pub b4: ai_real,
    pub c1: ai_real,
    pub c2: ai_real,
    pub c3: ai_real,
    pub c4: ai_real,
    pub d1: ai_real,
    pub d2: ai_real,
    pub d3: ai_real,
    pub d4: ai_real,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiQuaternion {
    pub w: ai_real,
    pub x: ai_real,
    pub y: ai_real,
    pub z: ai_real,
}
pub type ai_int32 = i32;
pub type ai_uint32 = u32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiPlane {
    pub a: ai_real,
    pub b: ai_real,
    pub c: ai_real,
    pub d: ai_real,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiRay {
    pub pos: aiVector3D,
    pub dir: aiVector3D,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiColor3D {
    pub r: f32,
    pub g: f32,
    pub b: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiString {
    pub length: ai_uint32,
    pub data: [::std::os::raw::c_char; 1024usize],
}
impl Default for aiString {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiReturn {
    aiReturn_SUCCESS = 0,
    aiReturn_FAILURE = -1,
    aiReturn_OUTOFMEMORY = -3,
    _AI_ENFORCE_ENUM_SIZE = 2147483647,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiOrigin {
    aiOrigin_SET = 0,
    aiOrigin_CUR = 1,
    aiOrigin_END = 2,
    _AI_ORIGIN_ENFORCE_ENUM_SIZE = 2147483647,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiDefaultLogStream {
    aiDefaultLogStream_FILE = 1,
    aiDefaultLogStream_STDOUT = 2,
    aiDefaultLogStream_STDERR = 4,
    aiDefaultLogStream_DEBUGGER = 8,
    _AI_DLS_ENFORCE_ENUM_SIZE = 2147483647,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiMemoryInfo {
    pub textures: ::std::os::raw::c_uint,
    pub materials: ::std::os::raw::c_uint,
    pub meshes: ::std::os::raw::c_uint,
    pub nodes: ::std::os::raw::c_uint,
    pub animations: ::std::os::raw::c_uint,
    pub cameras: ::std::os::raw::c_uint,
    pub lights: ::std::os::raw::c_uint,
    pub total: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiBuffer {
    pub data: *const ::std::os::raw::c_char,
    pub end: *const ::std::os::raw::c_char,
}
impl Default for aiBuffer {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiImporterFlags {
    aiImporterFlags_SupportTextFlavour = 1,
    aiImporterFlags_SupportBinaryFlavour = 2,
    aiImporterFlags_SupportCompressedFlavour = 4,
    aiImporterFlags_LimitedSupport = 8,
    aiImporterFlags_Experimental = 16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiImporterDesc {
    pub mName: *const ::std::os::raw::c_char,
    pub mAuthor: *const ::std::os::raw::c_char,
    pub mMaintainer: *const ::std::os::raw::c_char,
    pub mComments: *const ::std::os::raw::c_char,
    pub mFlags: ::std::os::raw::c_uint,
    pub mMinMajor: ::std::os::raw::c_uint,
    pub mMinMinor: ::std::os::raw::c_uint,
    pub mMaxMajor: ::std::os::raw::c_uint,
    pub mMaxMinor: ::std::os::raw::c_uint,
    pub mFileExtensions: *const ::std::os::raw::c_char,
}
impl Default for aiImporterDesc {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn aiGetImporterDesc(extension: *const ::std::os::raw::c_char) -> *const aiImporterDesc;
}
pub type aiLogStreamCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const ::std::os::raw::c_char, arg2: *mut ::std::os::raw::c_char),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiLogStream {
    pub callback: aiLogStreamCallback,
    pub user: *mut ::std::os::raw::c_char,
}
impl Default for aiLogStream {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiPropertyStore {
    pub sentinel: ::std::os::raw::c_char,
}
pub type aiBool = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn aiImportFile(
        pFile: *const ::std::os::raw::c_char,
        pFlags: ::std::os::raw::c_uint,
    ) -> *const aiScene;
}
unsafe extern "C" {
    pub fn aiImportFileEx(
        pFile: *const ::std::os::raw::c_char,
        pFlags: ::std::os::raw::c_uint,
        pFS: *mut aiFileIO,
    ) -> *const aiScene;
}
unsafe extern "C" {
    pub fn aiImportFileExWithProperties(
        pFile: *const ::std::os::raw::c_char,
        pFlags: ::std::os::raw::c_uint,
        pFS: *mut aiFileIO,
        pProps: *const aiPropertyStore,
    ) -> *const aiScene;
}
unsafe extern "C" {
    pub fn aiImportFileFromMemory(
        pBuffer: *const ::std::os::raw::c_char,
        pLength: ::std::os::raw::c_uint,
        pFlags: ::std::os::raw::c_uint,
        pHint: *const ::std::os::raw::c_char,
    ) -> *const aiScene;
}
unsafe extern "C" {
    pub fn aiImportFileFromMemoryWithProperties(
        pBuffer: *const ::std::os::raw::c_char,
        pLength: ::std::os::raw::c_uint,
        pFlags: ::std::os::raw::c_uint,
        pHint: *const ::std::os::raw::c_char,
        pProps: *const aiPropertyStore,
    ) -> *const aiScene;
}
unsafe extern "C" {
    pub fn aiApplyPostProcessing(
        pScene: *const aiScene,
        pFlags: ::std::os::raw::c_uint,
    ) -> *const aiScene;
}
unsafe extern "C" {
    pub fn aiGetPredefinedLogStream(
        pStreams: aiDefaultLogStream,
        file: *const ::std::os::raw::c_char,
    ) -> aiLogStream;
}
unsafe extern "C" {
    pub fn aiAttachLogStream(stream: *const aiLogStream);
}
unsafe extern "C" {
    pub fn aiEnableVerboseLogging(d: aiBool);
}
unsafe extern "C" {
    pub fn aiDetachLogStream(stream: *const aiLogStream) -> aiReturn;
}
unsafe extern "C" {
    pub fn aiDetachAllLogStreams();
}
unsafe extern "C" {
    pub fn aiReleaseImport(pScene: *const aiScene);
}
unsafe extern "C" {
    pub fn aiGetErrorString() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn aiIsExtensionSupported(szExtension: *const ::std::os::raw::c_char) -> aiBool;
}
unsafe extern "C" {
    pub fn aiGetExtensionList(szOut: *mut aiString);
}
unsafe extern "C" {
    pub fn aiGetMemoryRequirements(pIn: *const aiScene, in_: *mut aiMemoryInfo);
}
unsafe extern "C" {
    pub fn aiGetEmbeddedTexture(
        pIn: *const aiScene,
        filename: *const ::std::os::raw::c_char,
    ) -> *const aiTexture;
}
unsafe extern "C" {
    pub fn aiCreatePropertyStore() -> *mut aiPropertyStore;
}
unsafe extern "C" {
    pub fn aiReleasePropertyStore(p: *mut aiPropertyStore);
}
unsafe extern "C" {
    pub fn aiSetImportPropertyInteger(
        store: *mut aiPropertyStore,
        szName: *const ::std::os::raw::c_char,
        value: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn aiSetImportPropertyFloat(
        store: *mut aiPropertyStore,
        szName: *const ::std::os::raw::c_char,
        value: ai_real,
    );
}
unsafe extern "C" {
    pub fn aiSetImportPropertyString(
        store: *mut aiPropertyStore,
        szName: *const ::std::os::raw::c_char,
        st: *const aiString,
    );
}
unsafe extern "C" {
    pub fn aiSetImportPropertyMatrix(
        store: *mut aiPropertyStore,
        szName: *const ::std::os::raw::c_char,
        mat: *const aiMatrix4x4,
    );
}
unsafe extern "C" {
    pub fn aiCreateQuaternionFromMatrix(quat: *mut aiQuaternion, mat: *const aiMatrix3x3);
}
unsafe extern "C" {
    pub fn aiDecomposeMatrix(
        mat: *const aiMatrix4x4,
        scaling: *mut aiVector3D,
        rotation: *mut aiQuaternion,
        position: *mut aiVector3D,
    );
}
unsafe extern "C" {
    pub fn aiTransposeMatrix4(mat: *mut aiMatrix4x4);
}
unsafe extern "C" {
    pub fn aiTransposeMatrix3(mat: *mut aiMatrix3x3);
}
unsafe extern "C" {
    pub fn aiTransformVecByMatrix3(vec: *mut aiVector3D, mat: *const aiMatrix3x3);
}
unsafe extern "C" {
    pub fn aiTransformVecByMatrix4(vec: *mut aiVector3D, mat: *const aiMatrix4x4);
}
unsafe extern "C" {
    pub fn aiMultiplyMatrix4(dst: *mut aiMatrix4x4, src: *const aiMatrix4x4);
}
unsafe extern "C" {
    pub fn aiMultiplyMatrix3(dst: *mut aiMatrix3x3, src: *const aiMatrix3x3);
}
unsafe extern "C" {
    pub fn aiIdentityMatrix3(mat: *mut aiMatrix3x3);
}
unsafe extern "C" {
    pub fn aiIdentityMatrix4(mat: *mut aiMatrix4x4);
}
unsafe extern "C" {
    pub fn aiGetImportFormatCount() -> usize;
}
unsafe extern "C" {
    pub fn aiGetImportFormatDescription(pIndex: usize) -> *const aiImporterDesc;
}
unsafe extern "C" {
    pub fn aiVector2AreEqual(a: *const aiVector2D, b: *const aiVector2D) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiVector2AreEqualEpsilon(
        a: *const aiVector2D,
        b: *const aiVector2D,
        epsilon: f32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiVector2Add(dst: *mut aiVector2D, src: *const aiVector2D);
}
unsafe extern "C" {
    pub fn aiVector2Subtract(dst: *mut aiVector2D, src: *const aiVector2D);
}
unsafe extern "C" {
    pub fn aiVector2Scale(dst: *mut aiVector2D, s: f32);
}
unsafe extern "C" {
    pub fn aiVector2SymMul(dst: *mut aiVector2D, other: *const aiVector2D);
}
unsafe extern "C" {
    pub fn aiVector2DivideByScalar(dst: *mut aiVector2D, s: f32);
}
unsafe extern "C" {
    pub fn aiVector2DivideByVector(dst: *mut aiVector2D, v: *mut aiVector2D);
}
unsafe extern "C" {
    pub fn aiVector2Length(v: *const aiVector2D) -> ai_real;
}
unsafe extern "C" {
    pub fn aiVector2SquareLength(v: *const aiVector2D) -> ai_real;
}
unsafe extern "C" {
    pub fn aiVector2Negate(dst: *mut aiVector2D);
}
unsafe extern "C" {
    pub fn aiVector2DotProduct(a: *const aiVector2D, b: *const aiVector2D) -> ai_real;
}
unsafe extern "C" {
    pub fn aiVector2Normalize(v: *mut aiVector2D);
}
unsafe extern "C" {
    pub fn aiVector3AreEqual(a: *const aiVector3D, b: *const aiVector3D) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiVector3AreEqualEpsilon(
        a: *const aiVector3D,
        b: *const aiVector3D,
        epsilon: f32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiVector3LessThan(a: *const aiVector3D, b: *const aiVector3D) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiVector3Add(dst: *mut aiVector3D, src: *const aiVector3D);
}
unsafe extern "C" {
    pub fn aiVector3Subtract(dst: *mut aiVector3D, src: *const aiVector3D);
}
unsafe extern "C" {
    pub fn aiVector3Scale(dst: *mut aiVector3D, s: f32);
}
unsafe extern "C" {
    pub fn aiVector3SymMul(dst: *mut aiVector3D, other: *const aiVector3D);
}
unsafe extern "C" {
    pub fn aiVector3DivideByScalar(dst: *mut aiVector3D, s: f32);
}
unsafe extern "C" {
    pub fn aiVector3DivideByVector(dst: *mut aiVector3D, v: *mut aiVector3D);
}
unsafe extern "C" {
    pub fn aiVector3Length(v: *const aiVector3D) -> ai_real;
}
unsafe extern "C" {
    pub fn aiVector3SquareLength(v: *const aiVector3D) -> ai_real;
}
unsafe extern "C" {
    pub fn aiVector3Negate(dst: *mut aiVector3D);
}
unsafe extern "C" {
    pub fn aiVector3DotProduct(a: *const aiVector3D, b: *const aiVector3D) -> ai_real;
}
unsafe extern "C" {
    pub fn aiVector3CrossProduct(dst: *mut aiVector3D, a: *const aiVector3D, b: *const aiVector3D);
}
unsafe extern "C" {
    pub fn aiVector3Normalize(v: *mut aiVector3D);
}
unsafe extern "C" {
    pub fn aiVector3NormalizeSafe(v: *mut aiVector3D);
}
unsafe extern "C" {
    pub fn aiVector3RotateByQuaternion(v: *mut aiVector3D, q: *const aiQuaternion);
}
unsafe extern "C" {
    pub fn aiMatrix3FromMatrix4(dst: *mut aiMatrix3x3, mat: *const aiMatrix4x4);
}
unsafe extern "C" {
    pub fn aiMatrix3FromQuaternion(mat: *mut aiMatrix3x3, q: *const aiQuaternion);
}
unsafe extern "C" {
    pub fn aiMatrix3AreEqual(a: *const aiMatrix3x3, b: *const aiMatrix3x3)
    -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiMatrix3AreEqualEpsilon(
        a: *const aiMatrix3x3,
        b: *const aiMatrix3x3,
        epsilon: f32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiMatrix3Inverse(mat: *mut aiMatrix3x3);
}
unsafe extern "C" {
    pub fn aiMatrix3Determinant(mat: *const aiMatrix3x3) -> ai_real;
}
unsafe extern "C" {
    pub fn aiMatrix3RotationZ(mat: *mut aiMatrix3x3, angle: f32);
}
unsafe extern "C" {
    pub fn aiMatrix3FromRotationAroundAxis(
        mat: *mut aiMatrix3x3,
        axis: *const aiVector3D,
        angle: f32,
    );
}
unsafe extern "C" {
    pub fn aiMatrix3Translation(mat: *mut aiMatrix3x3, translation: *const aiVector2D);
}
unsafe extern "C" {
    pub fn aiMatrix3FromTo(mat: *mut aiMatrix3x3, from: *const aiVector3D, to: *const aiVector3D);
}
unsafe extern "C" {
    pub fn aiMatrix4FromMatrix3(dst: *mut aiMatrix4x4, mat: *const aiMatrix3x3);
}
unsafe extern "C" {
    pub fn aiMatrix4FromScalingQuaternionPosition(
        mat: *mut aiMatrix4x4,
        scaling: *const aiVector3D,
        rotation: *const aiQuaternion,
        position: *const aiVector3D,
    );
}
unsafe extern "C" {
    pub fn aiMatrix4Add(dst: *mut aiMatrix4x4, src: *const aiMatrix4x4);
}
unsafe extern "C" {
    pub fn aiMatrix4AreEqual(a: *const aiMatrix4x4, b: *const aiMatrix4x4)
    -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiMatrix4AreEqualEpsilon(
        a: *const aiMatrix4x4,
        b: *const aiMatrix4x4,
        epsilon: f32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiMatrix4Inverse(mat: *mut aiMatrix4x4);
}
unsafe extern "C" {
    pub fn aiMatrix4Determinant(mat: *const aiMatrix4x4) -> ai_real;
}
unsafe extern "C" {
    pub fn aiMatrix4IsIdentity(mat: *const aiMatrix4x4) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiMatrix4DecomposeIntoScalingEulerAnglesPosition(
        mat: *const aiMatrix4x4,
        scaling: *mut aiVector3D,
        rotation: *mut aiVector3D,
        position: *mut aiVector3D,
    );
}
unsafe extern "C" {
    pub fn aiMatrix4DecomposeIntoScalingAxisAnglePosition(
        mat: *const aiMatrix4x4,
        scaling: *mut aiVector3D,
        axis: *mut aiVector3D,
        angle: *mut ai_real,
        position: *mut aiVector3D,
    );
}
unsafe extern "C" {
    pub fn aiMatrix4DecomposeNoScaling(
        mat: *const aiMatrix4x4,
        rotation: *mut aiQuaternion,
        position: *mut aiVector3D,
    );
}
unsafe extern "C" {
    pub fn aiMatrix4FromEulerAngles(mat: *mut aiMatrix4x4, x: f32, y: f32, z: f32);
}
unsafe extern "C" {
    pub fn aiMatrix4RotationX(mat: *mut aiMatrix4x4, angle: f32);
}
unsafe extern "C" {
    pub fn aiMatrix4RotationY(mat: *mut aiMatrix4x4, angle: f32);
}
unsafe extern "C" {
    pub fn aiMatrix4RotationZ(mat: *mut aiMatrix4x4, angle: f32);
}
unsafe extern "C" {
    pub fn aiMatrix4FromRotationAroundAxis(
        mat: *mut aiMatrix4x4,
        axis: *const aiVector3D,
        angle: f32,
    );
}
unsafe extern "C" {
    pub fn aiMatrix4Translation(mat: *mut aiMatrix4x4, translation: *const aiVector3D);
}
unsafe extern "C" {
    pub fn aiMatrix4Scaling(mat: *mut aiMatrix4x4, scaling: *const aiVector3D);
}
unsafe extern "C" {
    pub fn aiMatrix4FromTo(mat: *mut aiMatrix4x4, from: *const aiVector3D, to: *const aiVector3D);
}
unsafe extern "C" {
    pub fn aiQuaternionFromEulerAngles(q: *mut aiQuaternion, x: f32, y: f32, z: f32);
}
unsafe extern "C" {
    pub fn aiQuaternionFromAxisAngle(q: *mut aiQuaternion, axis: *const aiVector3D, angle: f32);
}
unsafe extern "C" {
    pub fn aiQuaternionFromNormalizedQuaternion(
        q: *mut aiQuaternion,
        normalized: *const aiVector3D,
    );
}
unsafe extern "C" {
    pub fn aiQuaternionAreEqual(
        a: *const aiQuaternion,
        b: *const aiQuaternion,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiQuaternionAreEqualEpsilon(
        a: *const aiQuaternion,
        b: *const aiQuaternion,
        epsilon: f32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn aiQuaternionNormalize(q: *mut aiQuaternion);
}
unsafe extern "C" {
    pub fn aiQuaternionConjugate(q: *mut aiQuaternion);
}
unsafe extern "C" {
    pub fn aiQuaternionMultiply(dst: *mut aiQuaternion, q: *const aiQuaternion);
}
unsafe extern "C" {
    pub fn aiQuaternionInterpolate(
        dst: *mut aiQuaternion,
        start: *const aiQuaternion,
        end: *const aiQuaternion,
        factor: f32,
    );
}
#[repr(C, packed)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiTexel {
    pub b: ::std::os::raw::c_uchar,
    pub g: ::std::os::raw::c_uchar,
    pub r: ::std::os::raw::c_uchar,
    pub a: ::std::os::raw::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiTexture {
    pub mWidth: ::std::os::raw::c_uint,
    pub mHeight: ::std::os::raw::c_uint,
    pub achFormatHint: [::std::os::raw::c_char; 9usize],
    pub pcData: *mut aiTexel,
    pub mFilename: aiString,
}
impl Default for aiTexture {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiAABB {
    pub mMin: aiVector3D,
    pub mMax: aiVector3D,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiFace {
    pub mNumIndices: ::std::os::raw::c_uint,
    pub mIndices: *mut ::std::os::raw::c_uint,
}
impl Default for aiFace {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiVertexWeight {
    pub mVertexId: ::std::os::raw::c_uint,
    pub mWeight: ai_real,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiBone {
    pub mName: aiString,
    pub mNumWeights: ::std::os::raw::c_uint,
    pub mArmature: *mut aiNode,
    pub mNode: *mut aiNode,
    pub mWeights: *mut aiVertexWeight,
    pub mOffsetMatrix: aiMatrix4x4,
}
impl Default for aiBone {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiPrimitiveType {
    aiPrimitiveType_POINT = 1,
    aiPrimitiveType_LINE = 2,
    aiPrimitiveType_TRIANGLE = 4,
    aiPrimitiveType_POLYGON = 8,
    aiPrimitiveType_NGONEncodingFlag = 16,
    _aiPrimitiveType_Force32Bit = 2147483647,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiAnimMesh {
    pub mName: aiString,
    pub mVertices: *mut aiVector3D,
    pub mNormals: *mut aiVector3D,
    pub mTangents: *mut aiVector3D,
    pub mBitangents: *mut aiVector3D,
    pub mColors: [*mut aiColor4D; 8usize],
    pub mTextureCoords: [*mut aiVector3D; 8usize],
    pub mNumVertices: ::std::os::raw::c_uint,
    pub mWeight: f32,
}
impl Default for aiAnimMesh {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiMorphingMethod {
    aiMorphingMethod_UNKNOWN = 0,
    aiMorphingMethod_VERTEX_BLEND = 1,
    aiMorphingMethod_MORPH_NORMALIZED = 2,
    aiMorphingMethod_MORPH_RELATIVE = 3,
    _aiMorphingMethod_Force32Bit = 2147483647,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiMesh {
    pub mPrimitiveTypes: ::std::os::raw::c_uint,
    pub mNumVertices: ::std::os::raw::c_uint,
    pub mNumFaces: ::std::os::raw::c_uint,
    pub mVertices: *mut aiVector3D,
    pub mNormals: *mut aiVector3D,
    pub mTangents: *mut aiVector3D,
    pub mBitangents: *mut aiVector3D,
    pub mColors: [*mut aiColor4D; 8usize],
    pub mTextureCoords: [*mut aiVector3D; 8usize],
    pub mNumUVComponents: [::std::os::raw::c_uint; 8usize],
    pub mFaces: *mut aiFace,
    pub mNumBones: ::std::os::raw::c_uint,
    pub mBones: *mut *mut aiBone,
    pub mMaterialIndex: ::std::os::raw::c_uint,
    pub mName: aiString,
    pub mNumAnimMeshes: ::std::os::raw::c_uint,
    pub mAnimMeshes: *mut *mut aiAnimMesh,
    pub mMethod: aiMorphingMethod,
    pub mAABB: aiAABB,
    pub mTextureCoordsNames: *mut *mut aiString,
}
impl Default for aiMesh {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiSkeletonBone {
    pub mParent: ::std::os::raw::c_int,
    pub mArmature: *mut aiNode,
    pub mNode: *mut aiNode,
    pub mNumnWeights: ::std::os::raw::c_uint,
    pub mMeshId: *mut aiMesh,
    pub mWeights: *mut aiVertexWeight,
    pub mOffsetMatrix: aiMatrix4x4,
    pub mLocalMatrix: aiMatrix4x4,
}
impl Default for aiSkeletonBone {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiSkeleton {
    pub mName: aiString,
    pub mNumBones: ::std::os::raw::c_uint,
    pub mBones: *mut *mut aiSkeletonBone,
}
impl Default for aiSkeleton {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiLightSourceType {
    aiLightSource_UNDEFINED = 0,
    aiLightSource_DIRECTIONAL = 1,
    aiLightSource_POINT = 2,
    aiLightSource_SPOT = 3,
    aiLightSource_AMBIENT = 4,
    aiLightSource_AREA = 5,
    _aiLightSource_Force32Bit = 2147483647,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiLight {
    pub mName: aiString,
    pub mType: aiLightSourceType,
    pub mPosition: aiVector3D,
    pub mDirection: aiVector3D,
    pub mUp: aiVector3D,
    pub mAttenuationConstant: f32,
    pub mAttenuationLinear: f32,
    pub mAttenuationQuadratic: f32,
    pub mColorDiffuse: aiColor3D,
    pub mColorSpecular: aiColor3D,
    pub mColorAmbient: aiColor3D,
    pub mAngleInnerCone: f32,
    pub mAngleOuterCone: f32,
    pub mSize: aiVector2D,
}
impl Default for aiLight {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiCamera {
    pub mName: aiString,
    pub mPosition: aiVector3D,
    pub mUp: aiVector3D,
    pub mLookAt: aiVector3D,
    pub mHorizontalFOV: f32,
    pub mClipPlaneNear: f32,
    pub mClipPlaneFar: f32,
    pub mAspect: f32,
    pub mOrthographicWidth: f32,
}
impl Default for aiCamera {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiTextureOp {
    aiTextureOp_Multiply = 0,
    aiTextureOp_Add = 1,
    aiTextureOp_Subtract = 2,
    aiTextureOp_Divide = 3,
    aiTextureOp_SmoothAdd = 4,
    aiTextureOp_SignedAdd = 5,
    _aiTextureOp_Force32Bit = 2147483647,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiTextureMapMode {
    aiTextureMapMode_Wrap = 0,
    aiTextureMapMode_Clamp = 1,
    aiTextureMapMode_Decal = 3,
    aiTextureMapMode_Mirror = 2,
    _aiTextureMapMode_Force32Bit = 2147483647,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiTextureMapping {
    aiTextureMapping_UV = 0,
    aiTextureMapping_SPHERE = 1,
    aiTextureMapping_CYLINDER = 2,
    aiTextureMapping_BOX = 3,
    aiTextureMapping_PLANE = 4,
    aiTextureMapping_OTHER = 5,
    _aiTextureMapping_Force32Bit = 2147483647,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiTextureType {
    aiTextureType_NONE = 0,
    aiTextureType_DIFFUSE = 1,
    aiTextureType_SPECULAR = 2,
    aiTextureType_AMBIENT = 3,
    aiTextureType_EMISSIVE = 4,
    aiTextureType_HEIGHT = 5,
    aiTextureType_NORMALS = 6,
    aiTextureType_SHININESS = 7,
    aiTextureType_OPACITY = 8,
    aiTextureType_DISPLACEMENT = 9,
    aiTextureType_LIGHTMAP = 10,
    aiTextureType_REFLECTION = 11,
    aiTextureType_BASE_COLOR = 12,
    aiTextureType_NORMAL_CAMERA = 13,
    aiTextureType_EMISSION_COLOR = 14,
    aiTextureType_METALNESS = 15,
    aiTextureType_DIFFUSE_ROUGHNESS = 16,
    aiTextureType_AMBIENT_OCCLUSION = 17,
    aiTextureType_UNKNOWN = 18,
    aiTextureType_SHEEN = 19,
    aiTextureType_CLEARCOAT = 20,
    aiTextureType_TRANSMISSION = 21,
    aiTextureType_MAYA_BASE = 22,
    aiTextureType_MAYA_SPECULAR = 23,
    aiTextureType_MAYA_SPECULAR_COLOR = 24,
    aiTextureType_MAYA_SPECULAR_ROUGHNESS = 25,
    aiTextureType_ANISOTROPY = 26,
    aiTextureType_GLTF_METALLIC_ROUGHNESS = 27,
    _aiTextureType_Force32Bit = 2147483647,
}
unsafe extern "C" {
    pub fn aiTextureTypeToString(in_: aiTextureType) -> *const ::std::os::raw::c_char;
}
impl aiShadingMode {
    pub const aiShadingMode_Unlit: aiShadingMode = aiShadingMode::aiShadingMode_NoShading;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiShadingMode {
    aiShadingMode_Flat = 1,
    aiShadingMode_Gouraud = 2,
    aiShadingMode_Phong = 3,
    aiShadingMode_Blinn = 4,
    aiShadingMode_Toon = 5,
    aiShadingMode_OrenNayar = 6,
    aiShadingMode_Minnaert = 7,
    aiShadingMode_CookTorrance = 8,
    aiShadingMode_NoShading = 9,
    aiShadingMode_Fresnel = 10,
    aiShadingMode_PBR_BRDF = 11,
    _aiShadingMode_Force32Bit = 2147483647,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiTextureFlags {
    aiTextureFlags_Invert = 1,
    aiTextureFlags_UseAlpha = 2,
    aiTextureFlags_IgnoreAlpha = 4,
    _aiTextureFlags_Force32Bit = 2147483647,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiBlendMode {
    aiBlendMode_Default = 0,
    aiBlendMode_Additive = 1,
    _aiBlendMode_Force32Bit = 2147483647,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiUVTransform {
    pub mTranslation: aiVector2D,
    pub mScaling: aiVector2D,
    pub mRotation: ai_real,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiPropertyTypeInfo {
    aiPTI_Float = 1,
    aiPTI_Double = 2,
    aiPTI_String = 3,
    aiPTI_Integer = 4,
    aiPTI_Buffer = 5,
    _aiPTI_Force32Bit = 2147483647,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiMaterialProperty {
    pub mKey: aiString,
    pub mSemantic: ::std::os::raw::c_uint,
    pub mIndex: ::std::os::raw::c_uint,
    pub mDataLength: ::std::os::raw::c_uint,
    pub mType: aiPropertyTypeInfo,
    pub mData: *mut ::std::os::raw::c_char,
}
impl Default for aiMaterialProperty {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiMaterial {
    pub mProperties: *mut *mut aiMaterialProperty,
    pub mNumProperties: ::std::os::raw::c_uint,
    pub mNumAllocated: ::std::os::raw::c_uint,
}
impl Default for aiMaterial {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn aiGetMaterialProperty(
        pMat: *const aiMaterial,
        pKey: *const ::std::os::raw::c_char,
        type_: ::std::os::raw::c_uint,
        index: ::std::os::raw::c_uint,
        pPropOut: *mut *const aiMaterialProperty,
    ) -> aiReturn;
}
unsafe extern "C" {
    pub fn aiGetMaterialFloatArray(
        pMat: *const aiMaterial,
        pKey: *const ::std::os::raw::c_char,
        type_: ::std::os::raw::c_uint,
        index: ::std::os::raw::c_uint,
        pOut: *mut ai_real,
        pMax: *mut ::std::os::raw::c_uint,
    ) -> aiReturn;
}
unsafe extern "C" {
    pub fn aiGetMaterialIntegerArray(
        pMat: *const aiMaterial,
        pKey: *const ::std::os::raw::c_char,
        type_: ::std::os::raw::c_uint,
        index: ::std::os::raw::c_uint,
        pOut: *mut ::std::os::raw::c_int,
        pMax: *mut ::std::os::raw::c_uint,
    ) -> aiReturn;
}
unsafe extern "C" {
    pub fn aiGetMaterialColor(
        pMat: *const aiMaterial,
        pKey: *const ::std::os::raw::c_char,
        type_: ::std::os::raw::c_uint,
        index: ::std::os::raw::c_uint,
        pOut: *mut aiColor4D,
    ) -> aiReturn;
}
unsafe extern "C" {
    pub fn aiGetMaterialUVTransform(
        pMat: *const aiMaterial,
        pKey: *const ::std::os::raw::c_char,
        type_: ::std::os::raw::c_uint,
        index: ::std::os::raw::c_uint,
        pOut: *mut aiUVTransform,
    ) -> aiReturn;
}
unsafe extern "C" {
    pub fn aiGetMaterialString(
        pMat: *const aiMaterial,
        pKey: *const ::std::os::raw::c_char,
        type_: ::std::os::raw::c_uint,
        index: ::std::os::raw::c_uint,
        pOut: *mut aiString,
    ) -> aiReturn;
}
unsafe extern "C" {
    pub fn aiGetMaterialTextureCount(
        pMat: *const aiMaterial,
        type_: aiTextureType,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn aiGetMaterialTexture(
        mat: *const aiMaterial,
        type_: aiTextureType,
        index: ::std::os::raw::c_uint,
        path: *mut aiString,
        mapping: *mut aiTextureMapping,
        uvindex: *mut ::std::os::raw::c_uint,
        blend: *mut ai_real,
        op: *mut aiTextureOp,
        mapmode: *mut aiTextureMapMode,
        flags: *mut ::std::os::raw::c_uint,
    ) -> aiReturn;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiAnimInterpolation {
    aiAnimInterpolation_Step = 0,
    aiAnimInterpolation_Linear = 1,
    aiAnimInterpolation_Spherical_Linear = 2,
    aiAnimInterpolation_Cubic_Spline = 3,
    _aiAnimInterpolation_Force32Bit = 2147483647,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiVectorKey {
    pub mTime: f64,
    pub mValue: aiVector3D,
    pub mInterpolation: aiAnimInterpolation,
}
impl Default for aiVectorKey {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiQuatKey {
    pub mTime: f64,
    pub mValue: aiQuaternion,
    pub mInterpolation: aiAnimInterpolation,
}
impl Default for aiQuatKey {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq)]
pub struct aiMeshKey {
    pub mTime: f64,
    pub mValue: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiMeshMorphKey {
    pub mTime: f64,
    pub mValues: *mut ::std::os::raw::c_uint,
    pub mWeights: *mut f64,
    pub mNumValuesAndWeights: ::std::os::raw::c_uint,
}
impl Default for aiMeshMorphKey {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiAnimBehaviour {
    aiAnimBehaviour_DEFAULT = 0,
    aiAnimBehaviour_CONSTANT = 1,
    aiAnimBehaviour_LINEAR = 2,
    aiAnimBehaviour_REPEAT = 3,
    _aiAnimBehaviour_Force32Bit = 2147483647,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiNodeAnim {
    pub mNodeName: aiString,
    pub mNumPositionKeys: ::std::os::raw::c_uint,
    pub mPositionKeys: *mut aiVectorKey,
    pub mNumRotationKeys: ::std::os::raw::c_uint,
    pub mRotationKeys: *mut aiQuatKey,
    pub mNumScalingKeys: ::std::os::raw::c_uint,
    pub mScalingKeys: *mut aiVectorKey,
    pub mPreState: aiAnimBehaviour,
    pub mPostState: aiAnimBehaviour,
}
impl Default for aiNodeAnim {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiMeshAnim {
    pub mName: aiString,
    pub mNumKeys: ::std::os::raw::c_uint,
    pub mKeys: *mut aiMeshKey,
}
impl Default for aiMeshAnim {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiMeshMorphAnim {
    pub mName: aiString,
    pub mNumKeys: ::std::os::raw::c_uint,
    pub mKeys: *mut aiMeshMorphKey,
}
impl Default for aiMeshMorphAnim {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiAnimation {
    pub mName: aiString,
    pub mDuration: f64,
    pub mTicksPerSecond: f64,
    pub mNumChannels: ::std::os::raw::c_uint,
    pub mChannels: *mut *mut aiNodeAnim,
    pub mNumMeshChannels: ::std::os::raw::c_uint,
    pub mMeshChannels: *mut *mut aiMeshAnim,
    pub mNumMorphMeshChannels: ::std::os::raw::c_uint,
    pub mMorphMeshChannels: *mut *mut aiMeshMorphAnim,
}
impl Default for aiAnimation {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiMetadataType {
    AI_BOOL = 0,
    AI_INT32 = 1,
    AI_UINT64 = 2,
    AI_FLOAT = 3,
    AI_DOUBLE = 4,
    AI_AISTRING = 5,
    AI_AIVECTOR3D = 6,
    AI_AIMETADATA = 7,
    AI_INT64 = 8,
    AI_UINT32 = 9,
    AI_META_MAX = 10,
    FORCE_32BIT = 2147483647,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiMetadataEntry {
    pub mType: aiMetadataType,
    pub mData: *mut ::std::os::raw::c_void,
}
impl Default for aiMetadataEntry {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiMetadata {
    pub mNumProperties: ::std::os::raw::c_uint,
    pub mKeys: *mut aiString,
    pub mValues: *mut aiMetadataEntry,
}
impl Default for aiMetadata {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiNode {
    pub mName: aiString,
    pub mTransformation: aiMatrix4x4,
    pub mParent: *mut aiNode,
    pub mNumChildren: ::std::os::raw::c_uint,
    pub mChildren: *mut *mut aiNode,
    pub mNumMeshes: ::std::os::raw::c_uint,
    pub mMeshes: *mut ::std::os::raw::c_uint,
    pub mMetaData: *mut aiMetadata,
}
impl Default for aiNode {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiScene {
    pub mFlags: ::std::os::raw::c_uint,
    pub mRootNode: *mut aiNode,
    pub mNumMeshes: ::std::os::raw::c_uint,
    pub mMeshes: *mut *mut aiMesh,
    pub mNumMaterials: ::std::os::raw::c_uint,
    pub mMaterials: *mut *mut aiMaterial,
    pub mNumAnimations: ::std::os::raw::c_uint,
    pub mAnimations: *mut *mut aiAnimation,
    pub mNumTextures: ::std::os::raw::c_uint,
    pub mTextures: *mut *mut aiTexture,
    pub mNumLights: ::std::os::raw::c_uint,
    pub mLights: *mut *mut aiLight,
    pub mNumCameras: ::std::os::raw::c_uint,
    pub mCameras: *mut *mut aiCamera,
    pub mMetaData: *mut aiMetadata,
    pub mName: aiString,
    pub mNumSkeletons: ::std::os::raw::c_uint,
    pub mSkeletons: *mut *mut aiSkeleton,
    pub mPrivate: *mut ::std::os::raw::c_char,
}
impl Default for aiScene {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiPostProcessSteps {
    aiProcess_CalcTangentSpace = 1,
    aiProcess_JoinIdenticalVertices = 2,
    aiProcess_MakeLeftHanded = 4,
    aiProcess_Triangulate = 8,
    aiProcess_RemoveComponent = 16,
    aiProcess_GenNormals = 32,
    aiProcess_GenSmoothNormals = 64,
    aiProcess_SplitLargeMeshes = 128,
    aiProcess_PreTransformVertices = 256,
    aiProcess_LimitBoneWeights = 512,
    aiProcess_ValidateDataStructure = 1024,
    aiProcess_ImproveCacheLocality = 2048,
    aiProcess_RemoveRedundantMaterials = 4096,
    aiProcess_FixInfacingNormals = 8192,
    aiProcess_PopulateArmatureData = 16384,
    aiProcess_SortByPType = 32768,
    aiProcess_FindDegenerates = 65536,
    aiProcess_FindInvalidData = 131072,
    aiProcess_GenUVCoords = 262144,
    aiProcess_TransformUVCoords = 524288,
    aiProcess_FindInstances = 1048576,
    aiProcess_OptimizeMeshes = 2097152,
    aiProcess_OptimizeGraph = 4194304,
    aiProcess_FlipUVs = 8388608,
    aiProcess_FlipWindingOrder = 16777216,
    aiProcess_SplitByBoneCount = 33554432,
    aiProcess_Debone = 67108864,
    aiProcess_GlobalScale = 134217728,
    aiProcess_EmbedTextures = 268435456,
    aiProcess_ForceGenNormals = 536870912,
    aiProcess_DropNormals = 1073741824,
    aiProcess_GenBoundingBoxes = 2147483648,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiExportFormatDesc {
    pub id: *const ::std::os::raw::c_char,
    pub description: *const ::std::os::raw::c_char,
    pub fileExtension: *const ::std::os::raw::c_char,
}
impl Default for aiExportFormatDesc {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn aiGetExportFormatCount() -> usize;
}
unsafe extern "C" {
    pub fn aiGetExportFormatDescription(pIndex: usize) -> *const aiExportFormatDesc;
}
unsafe extern "C" {
    pub fn aiReleaseExportFormatDescription(desc: *const aiExportFormatDesc);
}
unsafe extern "C" {
    pub fn aiCopyScene(pIn: *const aiScene, pOut: *mut *mut aiScene);
}
unsafe extern "C" {
    pub fn aiFreeScene(pIn: *const aiScene);
}
unsafe extern "C" {
    pub fn aiExportScene(
        pScene: *const aiScene,
        pFormatId: *const ::std::os::raw::c_char,
        pFileName: *const ::std::os::raw::c_char,
        pPreprocessing: ::std::os::raw::c_uint,
    ) -> aiReturn;
}
unsafe extern "C" {
    pub fn aiExportSceneEx(
        pScene: *const aiScene,
        pFormatId: *const ::std::os::raw::c_char,
        pFileName: *const ::std::os::raw::c_char,
        pIO: *mut aiFileIO,
        pPreprocessing: ::std::os::raw::c_uint,
    ) -> aiReturn;
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiExportDataBlob {
    pub size: usize,
    pub data: *mut ::std::os::raw::c_void,
    pub name: aiString,
    pub next: *mut aiExportDataBlob,
}
impl Default for aiExportDataBlob {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn aiExportSceneToBlob(
        pScene: *const aiScene,
        pFormatId: *const ::std::os::raw::c_char,
        pPreprocessing: ::std::os::raw::c_uint,
    ) -> *const aiExportDataBlob;
}
unsafe extern "C" {
    pub fn aiReleaseExportBlob(pData: *const aiExportDataBlob);
}
pub type aiFileWriteProc = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut aiFile,
        arg2: *const ::std::os::raw::c_char,
        arg3: usize,
        arg4: usize,
    ) -> usize,
>;
pub type aiFileReadProc = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut aiFile,
        arg2: *mut ::std::os::raw::c_char,
        arg3: usize,
        arg4: usize,
    ) -> usize,
>;
pub type aiFileTellProc = ::std::option::Option<unsafe extern "C" fn(arg1: *mut aiFile) -> usize>;
pub type aiFileFlushProc = ::std::option::Option<unsafe extern "C" fn(arg1: *mut aiFile)>;
pub type aiFileSeek = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut aiFile, arg2: usize, arg3: aiOrigin) -> aiReturn,
>;
pub type aiFileOpenProc = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut aiFileIO,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> *mut aiFile,
>;
pub type aiFileCloseProc =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut aiFileIO, arg2: *mut aiFile)>;
pub type aiUserData = *mut ::std::os::raw::c_char;
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiFileIO {
    pub OpenProc: aiFileOpenProc,
    pub CloseProc: aiFileCloseProc,
    pub UserData: aiUserData,
}
impl Default for aiFileIO {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct aiFile {
    pub ReadProc: aiFileReadProc,
    pub WriteProc: aiFileWriteProc,
    pub TellProc: aiFileTellProc,
    pub FileSizeProc: aiFileTellProc,
    pub SeekProc: aiFileSeek,
    pub FlushProc: aiFileFlushProc,
    pub UserData: aiUserData,
}
impl Default for aiFile {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    #[doc = " @brief Returns a string with legal copyright and licensing information\n  about Assimp. The string may include multiple lines.\n  @return Pointer to static string."]
    pub fn aiGetLegalString() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " @brief Returns the current patch version number of Assimp.\n  @return Patch version of the Assimp runtime the application was\n    linked/built against"]
    pub fn aiGetVersionPatch() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    #[doc = " @brief Returns the current minor version number of Assimp.\n  @return Minor version of the Assimp runtime the application was\n    linked/built against"]
    pub fn aiGetVersionMinor() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    #[doc = " @brief Returns the current major version number of Assimp.\n  @return Major version of the Assimp runtime the application was\n    linked/built against"]
    pub fn aiGetVersionMajor() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    #[doc = " @brief Returns the repository revision of the Assimp runtime.\n  @return SVN Repository revision number of the Assimp runtime the\n          application was linked/built against."]
    pub fn aiGetVersionRevision() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    #[doc = " @brief Returns the branch-name of the Assimp runtime.\n  @return The current branch name."]
    pub fn aiGetBranchName() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " @brief Returns assimp's compile flags\n  @return Any bitwise combination of the ASSIMP_CFLAGS_xxx constants."]
    pub fn aiGetCompileFlags() -> ::std::os::raw::c_uint;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum aiRustPropertyKind {
    aiRustPropertyKind_Integer = 0,
    aiRustPropertyKind_Float = 1,
    aiRustPropertyKind_String = 2,
    aiRustPropertyKind_Matrix4x4 = 3,
    aiRustPropertyKind_Boolean = 4,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct aiRustProperty {
    pub name: *const ::std::os::raw::c_char,
    pub kind: aiRustPropertyKind,
    pub int_value: ::std::os::raw::c_int,
    pub float_value: f32,
    pub string_value: *const ::std::os::raw::c_char,
    pub matrix_value: *mut ::std::os::raw::c_void,
}
impl Default for aiRustProperty {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type aiRustProgressCallback = ::std::option::Option<
    unsafe extern "C" fn(
        percentage: f32,
        message: *const ::std::os::raw::c_char,
        user: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
unsafe extern "C" {
    pub fn aiImportFileExWithProgressRust(
        path: *const ::std::os::raw::c_char,
        flags: ::std::os::raw::c_uint,
        file_io: *const aiFileIO,
        props: *const aiRustProperty,
        props_count: usize,
        progress_cb: aiRustProgressCallback,
        progress_user: *mut ::std::os::raw::c_void,
    ) -> *const aiScene;
}
unsafe extern "C" {
    pub fn aiImportFileFromMemoryWithProgressRust(
        data: *const ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
        flags: ::std::os::raw::c_uint,
        hint: *const ::std::os::raw::c_char,
        props: *const aiRustProperty,
        props_count: usize,
        progress_cb: aiRustProgressCallback,
        progress_user: *mut ::std::os::raw::c_void,
    ) -> *const aiScene;
}
unsafe extern "C" {
    pub fn aiGetLastErrorStringRust() -> *const ::std::os::raw::c_char;
}
